println("")
println("════════════════════════════════════════════════════════════")
println("                                                            ")
println("   ~~~~~ Part 1: see a unified view of your data   ~~~~~    ")
println("                                                            ")
println("  Within this demo the Kafka messages live within a Kafka  ")
println("  cluster exposed on port 9092. The Iceberg data meanwhile ")
println("  lives within MinIO at port 9001.                          ")
println("                                                            ")
println("  In Streambased parlance, the logical view over Kafka is  ")
println("  called the hotset, the logical view over Iceberg is      ")
println("  called the coldset, and, crucially, there is a third     ")
println("  view: the merged set, which contains all of the data.   ")
println("                                                            ")
println("  To see this, let's show the databases available for      ")
println("  querying through Apache Spark:                           ")
println("                                                            ")
spark.sql("SHOW DATABASES").show()
println("                                                            ")
println("  All of these databases are logical views, there is no    ")
println("  duplication of data.                                     ")
println("════════════════════════════════════════════════════════════")
println("")