github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: true


tasks:
  - name: breakstream
    before: |
      ./bin/start.sh

ports:
  # kafka1
  - port: 9092
    onOpen: ignore
  # schema registry
  - port: 8081
    onOpen: ignore
  # spark-iceberg
  - port: 4040
    onOpen: ignore
  - port: 4041
    onOpen: ignore
  - port: 15002
    onOpen: ignore
  - port: 10000
    onOpen: ignore
  - port: 10001
    onOpen: ignore
  # minio
  - port: 9001
    onOpen: ignore
  # directstream
  - port: 11000
    onOpen: ignore
  - port: 11001
    onOpen: ignore
  # hyperstream
  - port: 9088
    onOpen: ignore
  # ksi
  - port: 9192
    onOpen: ignore
  # slipstream
  - port: 3000
    onOpen: ignore
  # akhq
  - port: 9090
    onOpen: ignore
