println("")
println("════════════════════════════════════════════════════════════")
println("                                                            ")
println("  Welcome to this Streambased terminal demo!                ")
println("                                                            ")
println("  Streambased allows you to combine your Apache Kafka data  ")
println("  and Apache Iceberg data by using logical views over the   ")
println("  data as it exists on disk in Kafka, and in an Iceberg      ")
println("  data lake — with no copying of data                       ")
println("                                                            ")
println("  This demo has four parts:                                 ")
println("  - Kafka & Iceberg with a unified view.                    ")
println("  - Querying across Kafka & Iceberg.                      ")
println("  - Moving data from Kafka to Iceberg.                      ")
println("  - The Kafka view of Kafka & Iceberg.                      ")
println("                                                            ")
println("════════════════════════════════════════════════════════════")
println("")