services:
  ksi:
    environment:
      - KSI_COLD_STORAGE_TIMEOUT_MS=${KSI_COLD_STORAGE_TIMEOUT_MS:-120000}
      - KSI_SPARK_CATALOG_NAME=isk
      - KSI_ICEBERG_NAMESPACE=hotset
      - KSI_SCHEMA_REGISTRY_URL
      - KSI_SPARK_CATALOG_ACCESS_KEY
      - KSI_SPARK_CATALOG_SECRET
      - KSI_SLIPSTREAM_URL=http://slipstream:3000
      - KSI_SLIPSTREAM_API_KEY=${KSI_SLIPSTREAM_API_KEY:-sbpk_12345678}
