services:
  ksi:
    environment:
      - KSI_STREAMING_READER_ENABLED=${KSI_STREAMING_READER_ENABLED:-true}
      - KSI_RECORD_CACHE_MAX_BYTES=${KSI_RECORD_CACHE_MAX_BYTES:-104857600000}
      - KSI_PREFETCH_BATCH_COUNT=${KSI_PREFETCH_BATCH_COUNT:-4}
      - KSI_BATCH_SIZE=${KSI_BATCH_SIZE:-100000}
