
  jupyter:
    image: streambased/spark-iceberg:latest
    container_name: jupyter
    hostname: jupyter
    platform: linux/amd64
    depends_on:
      - directstream
      - rest
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=sbpk_12345678
      - AWS_SECRET_ACCESS_KEY=sbsk_12345678
      - DIRECTSTREAM_CATALOG_URI=http:\/\/directstream:11001
      - DIRECTSTREAM_S3_ENDPOINT=http:\/\/directstream:11000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - 8889:8888
    volumes:
      - ./notebooks:/home/iceberg/notebooks
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        cat /opt/spark/conf/spark-defaults-orig.conf \
          | sed -e "s/{{DIRECTSTREAM_CATALOG_URI}}/$$DIRECTSTREAM_CATALOG_URI/g" \
          | sed -e "s/{{DIRECTSTREAM_S3_ENDPOINT}}/$$DIRECTSTREAM_S3_ENDPOINT/g" \
          > /opt/spark/conf/spark-defaults.conf
        pip install --quiet seaborn plotly openai scipy
        exec pyspark-notebook
