println("")
println("Here is the schema for this Kafka topic:")
spark.sql("DESCRIBE isk.hotset.transactions").show()
println("Notice the additional metadata, highlighted below:")
println("")
println("+--------------------+--------------------+-------+")
println("| col_name           | data_type          |comment|")
println("+--------------------+--------------------+-------+")
println("| ...........        | ...........        | ..... |")
println("| kafka_partition    | int                | NULL  |")
println("| kafka_offset       | bigint             | NULL  |")
println("| kafka_ts           | timestamp_ntz      | NULL  |")
println("| ...........        | ...........        | ..... |")
println("+--------------------+--------------------+-------+")
println("")
println("Kafka metadata is also available in Iceberg tables, giving you greater visibility over your data.")

