println("")
println("════════════════════════════════════════════════════════════")
println("                                                            ")
println("        ~~~~~ Part 2: query your data ~~~~~                 ")
println("                                                            ")
println("  In Part 1, we showed a unified view of Kafka & Iceberg.  ")
println("  Each of the tables — hotset, coldset, and merged —       ")
println("  enables us to query its respective data system, or to   ")
println("  query all of the data at once.                           ")
println("                                                            ")
println("  This will be demonstrated in the following      ")
println("  seven sections, where we query each database in turn.     ")
println("                                                            ")
println("════════════════════════════════════════════════════════════")
println("")
